spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true   
  rabbitmq:
    host: 192.168.217.130
    port: 5672
    username: admin
    password: admin
server:
  port: 8201
  
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
eureka:
  client:
    service-url:
      defaultZone: http://eurka1:2001/eureka,http://eureka2:2002/eureka